Repository zeoflow/zson, pull requests merged in 2020-10, with the labels that each got.

#6 Created method to cast to another object
  .zeobot/config.yml
  app/build.gradle
  app/src/main/java/com/zeoflow/test/MainActivity.java
  app/src/main/java/com/zeoflow/test/models/ModelClassNew.java
  app/src/main/java/com/zeoflow/test/models/ModelClassOld.java
  build.gradle
  zson/gradle.properties
  zson/src/main/java/com/zeoflow/zson/Zson.java
  zson/src/main/java/com/zeoflow/zson/ZsonCast.java
Labels: @feature, @issue, @priority-medium

#9 Cast improved
  app/src/main/java/com/zeoflow/test/MainActivity.java
  zson/src/main/java/com/zeoflow/zson/Zson.java
  zson/src/main/java/com/zeoflow/zson/ZsonCast.java
Labels: @enhancement, @priority-medium

#12 Min SDK - 14
  build.gradle
Labels: @dependency-update, @priority-critical

#13 Changed min SDK to v21
  .gitignore
  build.gradle
  zson/gradle.properties
  zson/maven-push.gradle
Labels: @dependency-update, @maintenance, @priority-high
